Update campaign_data.py
kaincenteno/logincampaign pull request #2
Opened 2022-08-24 21:09 UTC by Daywhite83

Added July and August Login Campaign Items

2022-08-24 22:16 UTC, kaincenteno requested changes
thank you for the commit it's greatly appreciated :D 
Please fix indents (I know its annoying)  and I'll take another peek and see if everything is kosher

2022-08-24 22:16 UTC, kaincenteno commented on data/campaign_data.py
> +					16120,	# Redeyes
needs indent fix

2022-08-24 22:16 UTC, kaincenteno commented on data/campaign_data.py
> +					4064,   # Rem's Tale Ch.1
Indent fix

2022-08-24 22:16 UTC, kaincenteno commented on data/campaign_data.py
> +					],
indent fix

2022-08-24 22:16 UTC, kaincenteno commented on data/campaign_data.py
> +				],
indent fix

2022-08-24 22:16 UTC, kaincenteno commented on data/campaign_data.py
> +					10183,	# Cipher: Darrcuiln
indent fix

2022-08-24 22:16 UTC, kaincenteno commented on data/campaign_data.py
> +					3748,	# Leafkin Bed
indent fix

2022-08-24 22:16 UTC, kaincenteno commented on data/campaign_data.py
> +					3752,	# Colibri Bed
indent fix

2022-08-24 22:16 UTC, kaincenteno commented on data/campaign_data.py
> +					3887,	# Musichinery Kit
indent fix

2022-08-24 22:16 UTC, kaincenteno commented on data/campaign_data.py
> +				],
indent fix

2022-08-24 22:51 UTC, Daywhite83 reviewed
Hopefully fixed indent issue

2022-08-24 23:02 UTC, kaincenteno requested changes
last change and i'll merge, won't go and verify if itemID cuz #trust 

but besides that looks good thanks @Daywhite83  😄

2022-08-24 23:02 UTC, kaincenteno commented on data/campaign_data.py
> +					4064,    # Rem's Tale Ch.1
indent fix

2022-08-25 00:05 UTC, Daywhite83 reviewed
indent fixed hopefully

2022-08-25 00:10 UTC, kaincenteno approved these changes
just noticed an empty line but it looks good awesome work

2022-08-25 00:10 UTC, merged